### ISSUE TITLE
Manually set leading for Paragraph

### ISSUE THREAD

**Issue by 8bitgentleman** [jorisschellekens/ptext-release#10]
Is is possible to manually set the leading for the text in a paragraph?

**Comment by jorisschellekens** [comment]
Currently there is no easy way to achieve this.
The way Paragraph handles this is coded in the layout methods.

It splits the text in lines, and applies the same multiplied leading (factor 1.3) to each of those.

Feel free to submit a pull-request to have this parameter included in the Paragraph.
