### ISSUE TITLE
[Feature Request] Add margins to layout intilizations parameters

### ISSUE THREAD

**Issue by cdgriffith** [jorisschellekens/ptext-release#12]
Because `previous_y` is calculated on `__init__` and updates to `vertical_margins` do not seem to recalculate when its changed, this can lead to unexpected behavior.  Would be nice to be able to set the margins and column_width as part of the call to `SingleColumnLayout`.

For example, if I want to have a full page image, this is the current solution I came up with: 

```
width, height = Decimal(2550), Decimal(3509)

# create an empty Document
pdf = Document()

# add an empty Page
page = Page(width=width, height=height)
pdf.append_page(page)

# create full page layout
layout = SingleColumnLayout(page)
layout.previous_y += layout.vertical_margin
layout.horizontal_margin = 0
layout.vertical_margin = 0
layout.inter_column_margin = 0
layout.column_width = width

layout.add(pImage(Image.open("image.tif"), width=width, height=height))

 ```

Could just be approaching this use case the entirely wrong way, but does seem hard to manipulate margins in any way currently. 

Thanks!

**Comment by jorisschellekens** [comment]
Thanks for your feedback.
I have a new release coming up, in which the layout mechanism has been refactored quite a bit.

I'll check what happens, and make margins a bit more accessible.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
:mega: Fixed.

You can expect to be able to set horizontal and vertical margin in any instance of `PageLayout` in the next release.
If you don't set this argument in the constructor, it will default to 10% of the page-width/height (which is the current behaviour).

Kind regards,
Joris Schellekens

**Comment by marcofariasmx** [comment]
> 📣 Fixed.
> 
> You can expect to be able to set horizontal and vertical margin in any instance of `PageLayout` in the next release.
> If you don't set this argument in the constructor, it will default to 10% of the page-width/height (which is the current behaviour).
> 
> Kind regards,
> Joris Schellekens

Hello Joris, could you please provide an example of its implementation? I can't seem to get it to work and it may be an easy thing to look up for future people needing the same thing. Thanks.
