### ISSUE TITLE
Adding Grayscale images creates broken PDFs

### ISSUE THREAD

**Issue by cdgriffith** [jorisschellekens/ptext-release#13]
![bad pdf](https://user-images.githubusercontent.com/3275435/122677908-009f0880-d1aa-11eb-94d2-fbe42e1f6ed1.PNG)

```
from PIL import Image
from decimal import Decimal

from ptext.pdf.canvas.layout.page_layout import SingleColumnLayout
from ptext.pdf.document import Document
from ptext.pdf.page.page import Page
from ptext.pdf.pdf import PDF
from ptext.pdf.canvas.layout.image.image import Image as pImage

img = Image.open("test.jpg")
width, height = Decimal(img.width), Decimal(img.height)

pdf = Document()

page = Page(width=width, height=height)
pdf.append_page(page)

layout = SingleColumnLayout(page)

# Conversion to grayscale here as an example
# can also use 8-bit grayscale TIFF file or similar
layout.add(pImage(img.convert("L"), width=width, height=height))

# store the PDF
with open("output.pdf", "wb") as pdf_file_handle:
    PDF.dumps(pdf_file_handle, pdf)
```

Sometimes it will work properly without an error but opening the PDF gives the error above. 

Other times it will hit a recursion error. 

```
Traceback (most recent call last):
  File "C:/Users/Chris/PycharmProjects/scanfix/create_pdf_bad.py", line 22, in <module>
    layout.add(pImage(img.convert("L"), width=width, height=height))
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\page_layout.py", line 144, in add
    return self.add(layout_element)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\page_layout.py", line 144, in add
    return self.add(layout_element)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\page_layout.py", line 144, in add
    return self.add(layout_element)
  [Previous line repeated 984 more times]
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\page_layout.py", line 135, in add
    layout_rect = layout_element.layout(self.page, bounding_box=next_available_rect)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\layout_element.py", line 219, in layout
    return self.calculate_layout_box_and_do_layout(page, bounding_box)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\layout_element.py", line 271, in calculate_layout_box_and_do_layout
    final_layout_box = self._do_layout(page, bounding_box)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\layout_element.py", line 197, in _do_layout
    output_box = self._do_layout_without_padding(page, modified_bounding_box)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\image\image.py", line 106, in _do_layout_without_padding
    image_resource_name = self._get_image_resource_name(self.image, page)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\pdf\canvas\layout\image\image.py", line 52, in _get_image_resource_name
    page[Name("Resources")] = Dictionary().set_parent(page)  # type: ignore [attr-defined]
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\io\read\types.py", line 330, in __init__
    add_base_methods(self)
  File "C:\Users\Chris\PycharmProjects\scanfix\venv\lib\site-packages\ptext\io\read\types.py", line 138, in add_base_methods
    def get_event_listeners(self) -> typing.List["EventListener"]:
  File "C:\Program Files\Python38\lib\typing.py", line 258, in inner
    return cached(*args, **kwds)
  File "C:\Program Files\Python38\lib\typing.py", line 723, in __hash__
    return hash((self.__origin__, self.__args__))
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Temporary solution is to just do a `.convert("RGB")` on all the images, but that increases the size and does a needless conversion.

**Comment by jorisschellekens** [comment]
Can you provide an image for which the save method fails? And one for which it hits a recursion error?
That would really help me out when debugging this issue.

Kind regards,
Joris Schellekens

**Comment by cdgriffith** [comment]
It doesn't really matter what image you use, as long as it's being converted to grayscale (as done above with the `.covert('L')` ). Attached my test image (personal photo, free usage right for this one). 

![test](https://user-images.githubusercontent.com/3275435/122682916-bc1f6700-d1c1-11eb-92c8-c676ed586c61.jpg)

The recursion thing is not repeatable is the issue. It happens randomly just once every so often, was just smart enough to capture full traceback one time. Now that I'm trying to repeat it, can't seem to get it again. 

When it works without an error will produce a PDF with an issue like [bad.pdf](https://github.com/jorisschellekens/ptext-release/files/6682793/bad.pdf)

You are fast on these, thanks for the help, and great program!

**Comment by jorisschellekens** [comment]
Ah, I figured out the recursion error.
This is something I need to document a bit better.
But what's basically happening is the following:
- The user adds an Image to a Page, which has a PageLayout
- PageLayout attempts to perform layout, and checks the resulting bounding box of the element
- PageLayout then notices the bounding box is too big (basically, the LayoutElement was too big for the remaining space on the Page)
- PageLayout creates a new Page, initializes everything to start layout on the new Page, and recursively calls itself to attempt to add the LayoutElement to the new Page.

After a while, you get the insane stackoverflow.

**Comment by jorisschellekens** [comment]
I've changed some code, it should now never attempt layout on an element that is simply too big for the page.
And it gives a sensible error when it encounters such an element.

`        # content that is too large for the page should not be attempted to be laid out again
        if round(layout_rect.get_width(), 2) > round(self._column_width, 2):
            assert False, "%s is too wide to fit inside column / page." % layout_element.__class__.__name__
        if round(layout_rect.get_height(), 2) > round(self._page_height - 2 * self._vertical_margin):
            assert False, "%s is too tall to fit inside column / page." % layout_element.__class__.__name__`

**Comment by jorisschellekens** [comment]
That's bizarre,
I added a test that replicates your issue. And although I'm pretty sure the PDF is corrupt, it does somewhat render the image.

![image](https://user-images.githubusercontent.com/18642798/122687791-91143200-d218-11eb-9d77-74de9107cc8b.png)

**Comment by jorisschellekens** [comment]
I've added a temporary workaround of converting non-RGB-mode images to RGB before they are being written.
I added a test specifically for your usecase.
And I marked the spot in the code with a `TODO`
I'm now re-running one of the tests that measures the filesize impact of opening and storing a document using pText.

Kind regards,
Joris Schellekens

**Comment by jorisschellekens** [comment]
[output.pdf](https://github.com/jorisschellekens/ptext-release/files/6683099/output.pdf)

It seems to work now.
I've verified that Adobe opens this document without issues.

```python

    def test_write_document_with_image(self):

        # create empty document
        pdf: Document = Document()

        # create empty page
        page: Page = Page()

        # add page to document
        pdf.append_page(page)

        # add Image
        layout = SingleColumnLayout(page)

        # add test information
        layout.add(
            Table(number_of_columns=2, number_of_rows=3)
            .add(Paragraph("Date", font="Helvetica-Bold"))
            .add(Paragraph(datetime.now().strftime("%d/%m/%Y, %H:%M:%S")))
            .add(Paragraph("Test", font="Helvetica-Bold"))
            .add(Paragraph(Path(__file__).stem[0:5]))
            .add(Paragraph("Description", font="Helvetica-Bold"))
            .add(
                Paragraph(
                    "This test creates a PDF with an Image in it, this is specified by a URL. The Image is converted to grayscale before re-adding it to the Page."
                )
            )
            .set_padding_on_all_cells(Decimal(2), Decimal(2), Decimal(2), Decimal(2))
        )

        # build Image
        img: pImage = pImage(
                    "https://images.unsplash.com/photo-1597826368522-9f4cb5a6ba48?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw",
                )

        # convert to grayscale
        pil_image_002 = img._image.convert("L")

        # add image
        layout.add(pImage(pil_image_002,
                          horizontal_alignment=Alignment.CENTERED,
                          width=Decimal(256),
                          height=Decimal(256),
                          ))

        # write
        file = self.output_dir / "output.pdf"
        with open(file, "wb") as pdf_file_handle:
            PDF.dumps(pdf_file_handle, pdf)
```
