### ISSUE TITLE
In which units are the values of `get_bounding_boxes` function

### ISSUE THREAD

**Issue by dianjuar** [jorisschellekens/ptext-release#14]
The  example [1.3](https://github.com/jorisschellekens/ptext-release/blob/master/EXAMPLES.md#13-looking-for-a-regular-expression-in-a-document-using-regularexpressiontextextraction) of getting the coordinates of a regular expression, what are the units of those coodinates?

Ex:
```python
import json
import re

from ptext.pdf.pdf import PDF
from ptext.toolkit.text.regular_expression_text_extraction import (
    RegularExpressionTextExtraction,
)


# regex = r"\${sign-[^}]+}"
regex = r"signhere"
doc = None
l = RegularExpressionTextExtraction(regex)
with open("./MSA-contract-template.pdf", "rb") as in_file_handle:
    doc = PDF.loads(in_file_handle, [l])

    # export matches
    with open("sign_matches.json", "w") as json_file_handle:
        obj = []
        for m in l.get_all_matches(0):
            for bb in m.get_bounding_boxes():
                obj.append(
                    {
                        "text": m.string,
                        "x": int(bb.x),
                        "y": int(bb.y),
                        "width": int(bb.width),
                        "height": int(bb.height),
                    }
                )
        json_file_handle.write(json.dumps(obj, indent=4))

```

Which are the units of `bb.x` and `bb.y`, pixels? points? feets?

**Comment by jorisschellekens** [comment]
Hi Diego,

pText (in fact PDF itself) may expose you to  two unit systems.
First are the units for anything font related.
For instance, the width of space character might be defined as 250 units.

The second kind of units are dots. This is the unit used for anything that isn't font-related.
For instance the bounding box you've mentioned is specified in dots.

PDF uses 72 dots per inch.
You can easily verify this:

1. I've made a convenient enum containing all paper sizes:
https://github.com/jorisschellekens/ptext-release/blob/master/ptext/pdf/page/page_size.py

2. Let's take A4 (standard european paper size) as an example.
https://github.com/jorisschellekens/ptext-release/blob/b594e8438838f64e40222bb5e0fc3fcc63f768ba/ptext/pdf/page/page_size.py#L27

3. A4 is 595 dots wide.
595 / 72 = 8.26388888889 inches = 20.9902778 centimeters

4. Now let's lookup the width of an A4 paper:
https://www.google.com/search?q=a4+paper+size

That seems to fit (taking into account some rounding error)

Kind regards,
Joris Schellekens
