### ISSUE TITLE
Bit improvement of Examples.md

### ISSUE THREAD

**Issue by diego-rapoport** [jorisschellekens/ptext-release#4]
So I really like what you're building here and I already saw a closed issue about importing things from the library, and if it wasn't for autocompletion I probably would be stuck using the library. The thing is that some functionalities are very nested within the project, which it could be by design and I'm ok with that, but the details of import could also be inside Examples.md. I don't have a problem to make a pull request for that, just checking if this makes any sense.

**Comment by jorisschellekens** [comment]
Hi there,

So perhaps I should add some documentation explaining the package layout?

Kind regards,
Joris
