### ISSUE TITLE
Add requirements to setup.py

### ISSUE THREAD

**Issue by covertspartan** [jorisschellekens/ptext-release#5]
It would be nice if the contents of `requirements.txt` were added to `setup.py` so that pip would pick them up automatically when doing a pip install. A pip install without requirments is only half complete :D

I offten use something like this to avoid having requirments duplicated in two places: https://stackoverflow.com/a/14399775

Otherwise, seems like a fun project so far!

**Comment by jorisschellekens** [comment]
Hi there,

I tried following the link you provided.
But this apparently does not work for 2 of my dependencies (which are just GitHub projects).
If you know how to do this, please submit a pull request.

Kind regards,
Joris
