### ISSUE TITLE
Problem with JSON example

### ISSUE THREAD

**Issue by Masynchin** [jorisschellekens/ptext-release#6]
There is a bug in https://github.com/jorisschellekens/ptext-release/blob/master/EXAMPLES.md#181-exporting-a-pdf-as-json with `doc.to_json_serializable(doc)` which should be `doc.to_json_serializable()`

**Comment by jorisschellekens** [comment]
Thanks. I'll change it asap.
It might take until this weekend before my changes in the dev repo get ported to the release repo though.
