### ISSUE TITLE
Sources too thick

### ISSUE THREAD

**Issue by tieugene** [jorisschellekens/ptext-release#8]
60MB of sources - it is vary, vary big tarball.
Including 20MB of well-known specifications and 15MB of nice pictures into sources is not good idea too.

**Comment by jorisschellekens** [comment]
Thanks for your feedback. I'm new to deploying stuff on PyPi. I don't know whether PyPi would include those.

Personally, I would keep the specs in the source. That way anyone that wants to collaborate immediately has a copy of the spec.

I also reference the spec several times in the code documentation. So I feel I should at least include it in sources.

But I can see about removing it from the release (if it's in there).

Would that be a good compromise?

**Comment by tieugene** [comment]
> But I can see about removing it from the release (if it's in there).
> Would that be a good compromise?

Yes, good idea.
Maybe adding doc as extra tarball in Assets will be better.
