### ISSUE TITLE
Extra dir installing

### ISSUE THREAD

**Issue by tieugene** [jorisschellekens/ptext-release#9]
/usr/lib/python*/site-packages/tests/ - redundant on normal system-wide installation.

**Comment by jorisschellekens** [comment]
If you can, please create a pull-request to remove this from the release package (and only from the release of course)

**Comment by jorisschellekens** [comment]
When installing using pip (which I assume is the default scenario), this directory (as well as the "doc" directory) are not copied.
In fact, only 1Mb is transferred.

```
Defaulting to user installation because normal site-packages is not writeable
Collecting ptext-joris-schellekens
  Downloading ptext_joris_schellekens-1.8.8-py3-none-any.whl (468 kB)
     |████████████████████████████████| 468 kB 1.8 MB/s 
Collecting setuptools~=51.1.1
  Downloading setuptools-51.1.2-py3-none-any.whl (784 kB)
     |████████████████████████████████| 784 kB 4.0 MB/s 
```
